#Persisted by DefaultConfig
#Sat Apr 11 12:34:37 CST 2026
spring.shardingsphere.datasource.ds0.min-idle=5
spring.shardingsphere.rules.sharding.tables.t_region.actual-data-nodes=ds0.t_region
spring.shardingsphere.rules.sharding.tables.t_order.table-strategy.standard.sharding-algorithm-name=order-month-sharding
spring.shardingsphere.datasource.ds0.max-wait=60000
spring.shardingsphere.datasource.ds0.url=jdbc\:mysql\://localhost\:3306/order_db?useUnicode\=true&characterEncoding\=utf8&useSSL\=false&serverTimezone\=Asia/Shanghai
spring.shardingsphere.datasource.ds0.password=12345678
spring.shardingsphere.datasource.ds0.username=root
server.port=9010
spring.shardingsphere.rules.sharding.tables.t_order_item.table-strategy.standard.sharding-column=code
spring.shardingsphere.rules.sharding.binding-tables=t_order,t_order_item
mybatis.type-aliases-package=com.zf.entity
spring.shardingsphere.rules.sharding.tables.t_order_item.table-strategy.standard.sharding-algorithm-name=order-item-month-sharding
rocketmq.producer.group=order-producer-group
spring.shardingsphere.rules.sharding.sharding-algorithms.order-month-sharding.type=CLASS_BASED
spring.shardingsphere.rules.sharding.tables.t_order.actual-data-nodes=ds0.t_order_$->{202601..202612},ds0.t_order
spring.shardingsphere.rules.sharding.tables.t_user.actual-data-nodes=ds0.t_user
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
spring.shardingsphere.rules.sharding.sharding-algorithms.order-item-month-sharding.props.strategy=STANDARD
spring.main.allow-bean-definition-overriding=true
mybatis.mapper-locations=classpath\:mapper/*.xml
spring.application.name=order-service
spring.shardingsphere.datasource.names=ds0
spring.shardingsphere.rules.sharding.tables.t_order_item.actual-data-nodes=ds0.t_order_item_$->{202601..202612},ds0.t_order_item
spring.shardingsphere.rules.sharding.sharding-algorithms.order-month-sharding.props.algorithmClassName=com.zf.sharding.OrderShardingAlgorithm
eureka.instance.prefer-ip-address=true
spring.shardingsphere.datasource.ds0.initial-size=5
spring.shardingsphere.datasource.ds0.type=com.alibaba.druid.pool.DruidDataSource
spring.shardingsphere.rules.sharding.tables.t_order.table-strategy.standard.sharding-column=code
spring.shardingsphere.rules.sharding.sharding-algorithms.order-item-month-sharding.type=CLASS_BASED
spring.shardingsphere.datasource.ds0.driver-class-name=com.mysql.cj.jdbc.Driver
eureka.instance.instance-id=${spring.application.name}\:${server.port}
spring.shardingsphere.props.sql-show=true
eureka.client.service-url.defaultZone=http\://localhost\:8761/eureka/
rocketmq.name-server=localhost\:9876
spring.shardingsphere.rules.sharding.sharding-algorithms.order-month-sharding.props.strategy=STANDARD
spring.shardingsphere.rules.sharding.sharding-algorithms.order-item-month-sharding.props.algorithmClassName=com.zf.sharding.OrderItemShardingAlgorithm
spring.shardingsphere.datasource.ds0.max-active=20
