services:
  # Apollo Config Service
  apollo-configservice:
    image: apolloconfig/apollo-configservice:2.1.0
    container_name: apollo-configservice
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      TZ: Asia/Shanghai
      SPRING_DATASOURCE_URL: "jdbc:mysql://host.docker.internal:3306/ApolloConfigDB?characterEncoding=utf8"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "12345678"
    ports:
      - "8080:8080"
    restart: on-failure

  # Apollo Admin Service
  apollo-adminservice:
    image: apolloconfig/apollo-adminservice:2.1.0
    container_name: apollo-adminservice
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      TZ: Asia/Shanghai
      SPRING_DATASOURCE_URL: "jdbc:mysql://host.docker.internal:3306/ApolloConfigDB?characterEncoding=utf8"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "12345678"
      APOLLO_CONFIG_SERVICE_URL: "http://apollo-configservice:8080"
      APOLLO_ADMIN_SERVICE_URL: "http://apollo-adminservice:8090"
    ports:
      - "8090:8090"
    depends_on:
      - apollo-configservice
    restart: on-failure

  # Apollo Portal
  apollo-portal:
    image: apolloconfig/apollo-portal:2.1.0
    container_name: apollo-portal
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      TZ: Asia/Shanghai
      SPRING_DATASOURCE_URL: "jdbc:mysql://host.docker.internal:3306/ApolloPortalDB?characterEncoding=utf8"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "12345678"
      APOLLO_PORTAL_ENVS: "dev"
      DEV_META: "http://apollo-configservice:8080"
    ports:
      - "8070:8070"
    depends_on:
      - apollo-adminservice
    restart: on-failure