server:
  port: 8083

spring:
  application:
    name: SENTINEL01
  cloud:
    nacos:
      discovery:
        server-addr: localhost
        port: 8848
    sentinel:
      transport:
        dashboard: localhost:8084
#        port: 8719
#        client-ip: localhost
#      enabled: true

